import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronRight } from "lucide-react";
import { ConfirmedForm } from "@/components/condominium/confirmed-form";
import { UnitForm } from "@/components/condominium/unit-form";
import { saveUnit } from "@/lib/condominium/actions";
import { requireCondominiumPermission } from "@/lib/condominium/access";
import { Alert } from "@/components/ui/feedback";
import { PersonRelationshipForm } from "@/components/condominium/person-form";
import { getCondominiumPeopleOptions, getRelationshipRows, todayInTimezone } from "@/lib/condominium/people-data";
import { occupancyTypeLabels } from "@/lib/condominium/format";

export const metadata={title:"Detalhe da unidade"};
const types:Record<string,string>={apartment:"Apartamento",house:"Casa",lot:"Lote",commercial:"Comercial",office:"Escritório",store:"Loja",other:"Outra"};
const statuses:Record<string,string>={active:"Ativa",inactive:"Inativa",under_construction:"Em construção",blocked:"Bloqueada"};
export default async function UnitDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{newPersonId?:string;relationship?:string;error?:string;saved?:string}>}){
  const {id}=await params;const flowParams=await searchParams;const {supabase,context}=await requireCondominiumPermission("units.read");
  const [{data:unit,error},{data:structures},{data:canManage}]=await Promise.all([
    supabase.from("units").select("id,structure_id,code,display_name,unit_type,floor,area,ownership_fraction,operational_status,notes,condominium_structures(name)").eq("id",id).eq("condominium_id",context.id).maybeSingle(),
    supabase.from("condominium_structures").select("id,name,status").eq("condominium_id",context.id),
    supabase.rpc("has_permission",{permission_code:"units.manage",target_condominium_id:context.id}),
  ]);
  if(error)return <Alert tone="error">Não foi possível carregar os dados da unidade agora.</Alert>;
  if(!unit)notFound();const structure=(unit.condominium_structures as unknown as {name:string}|null)?.name??"Sem estrutura";
  const permissions=await Promise.all(["ownerships.read","ownerships.manage","residents.read","residents.manage","financial_responsibilities.read","financial_responsibilities.manage"].map((permission_code)=>supabase.rpc("has_permission",{permission_code,target_condominium_id:context.id})));
  const [owners,occupancies,people,finance]=await Promise.all([
    permissions[0].data?getRelationshipRows(supabase,context.id,"ownership"):Promise.resolve({rows:[],error:null}),
    permissions[2].data?getRelationshipRows(supabase,context.id,"occupancy"):Promise.resolve({rows:[],error:null}),
    permissions.some((p)=>p.data===true)?getCondominiumPeopleOptions(supabase,context.id):Promise.resolve([]),
    permissions[4].data?supabase.from("unit_financial_responsibilities").select("id,person_id,starts_at,ends_at").eq("unit_id",id).eq("condominium_id",context.id).order("starts_at",{ascending:false}):Promise.resolve({data:[]}),
  ]);
  const ownerRows=owners.rows.filter((r)=>r.unit_id===id);const residentRows=occupancies.rows.filter((r)=>r.unit_id===id);
  const {data:condominium}=await supabase.from("condominiums").select("timezone").eq("id",context.id).maybeSingle();const localToday=todayInTimezone(condominium?.timezone||"America/Sao_Paulo");
  const financeIds=(finance.data||[]).map((r)=>r.person_id);const financePeople=financeIds.length?await supabase.from("people").select("id,full_name").in("id",financeIds):{data:[]};const financeNames=new Map((financePeople.data||[]).map((p)=>[p.id,p.full_name]));
  return <div className="cv-page">{flowParams.error&&<Alert tone="error">{flowParams.error}</Alert>}{flowParams.saved&&<Alert tone="success">Vínculo salvo.</Alert>}<div className="breadcrumbs"><Link href="/app/condominium">Condomínio</Link><ChevronRight size={14}/><Link href="/app/condominium/units">Unidades</Link><ChevronRight size={14}/><strong>{unit.code}</strong></div><section className="page-heading"><div><p className="page-overline">UNIDADE</p><h1>{unit.display_name||unit.code}</h1><p>{structure} · {types[unit.unit_type]??unit.unit_type}</p></div><span className={`cv-status cv-status-${unit.operational_status}`}>{statuses[unit.operational_status]??unit.operational_status}</span></section>
    <section className="cv-panel"><h2>Dados da unidade</h2>{canManage===true?<UnitForm structures={structures??[]} current={unit}/>:<div className="cv-read-grid"><p><span>Código</span><strong>{unit.code}</strong></p><p><span>Nome</span><strong>{unit.display_name||"Não informado"}</strong></p><p><span>Tipo</span><strong>{types[unit.unit_type]??unit.unit_type}</strong></p><p><span>Estrutura</span><strong>{structure}</strong></p><p><span>Andar</span><strong>{unit.floor||"Não informado"}</strong></p><p><span>Área</span><strong>{unit.area===null?"Não informada":`${new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(unit.area)} m²`}</strong></p><p><span>Fração ideal</span><strong>{unit.ownership_fraction===null?"Não informada":`${new Intl.NumberFormat("pt-BR",{maximumFractionDigits:6}).format(unit.ownership_fraction)}%`}</strong></p><p><span>Status</span><strong>{statuses[unit.operational_status]??unit.operational_status}</strong></p><p className="cv-read-wide"><span>Observações</span><strong>{unit.notes||"Não informado"}</strong></p></div>}</section>
    {permissions[0].data===true&&<section className="cv-panel"><h2>Proprietários</h2>{ownerRows.length?ownerRows.map((row)=><p key={row.id}><strong>{row.person_name}</strong> · {row.ownership_percentage===null?"participação não informada":`${row.ownership_percentage}%`} · {row.starts_at} → {row.ends_at||"sem término"}</p>):<p className="cv-muted">Nenhum proprietário registrado.</p>}{permissions[1].data===true&&<PersonRelationshipForm kind="ownership" people={people} units={[unit]} returnTo={`/app/condominium/units/${id}`} selectedPersonId={flowParams.relationship==="ownership"?flowParams.newPersonId:undefined} defaultUnitId={id}/>}</section>}
    {permissions[2].data===true&&<section className="cv-panel"><h2>Moradores</h2>{residentRows.length?residentRows.map((row)=><p key={row.id}><strong>{row.person_name}</strong> · {occupancyTypeLabels[row.occupancy_type||""]||"Outro"} {row.is_primary?"· Principal":""} · {row.starts_at} → {row.ends_at||"sem término"}</p>):<p className="cv-muted">Nenhum morador registrado.</p>}{permissions[3].data===true&&<PersonRelationshipForm kind="occupancy" people={people} units={[unit]} returnTo={`/app/condominium/units/${id}`} selectedPersonId={flowParams.relationship==="occupancy"?flowParams.newPersonId:undefined} defaultUnitId={id}/>}</section>}
    {permissions[4].data===true&&<section className="cv-panel"><h2>Responsável financeiro</h2>{(finance.data||[]).length?(finance.data||[]).map((row)=><p key={row.id}><strong>{financeNames.get(row.person_id)||"Pessoa"}</strong> · {row.starts_at>localToday?"Próximo":row.ends_at&&row.ends_at<=localToday?"Histórico":"Atual"} · {row.starts_at} → {row.ends_at||"sem término"}</p>):<p className="cv-muted">Nenhum responsável financeiro registrado.</p>}{permissions[5].data===true&&<PersonRelationshipForm kind="financial" people={people} units={[unit]} returnTo={`/app/condominium/units/${id}`} selectedPersonId={flowParams.relationship==="financial"?flowParams.newPersonId:undefined} defaultUnitId={id}/>}</section>}
    {canManage===true&&unit.operational_status!=="inactive"&&<section className="cv-panel"><h2>Inativar unidade</h2><p>A unidade continuará no histórico e poderá ser reativada depois.</p><ConfirmedForm action={saveUnit} confirmation={`Inativar a unidade ${unit.display_name||unit.code}?`}><input type="hidden" name="id" value={unit.id}/><input type="hidden" name="code" value={unit.code}/><input type="hidden" name="display_name" value={unit.display_name??""}/><input type="hidden" name="unit_type" value={unit.unit_type}/><input type="hidden" name="structure_id" value={unit.structure_id??""}/><input type="hidden" name="floor" value={unit.floor??""}/><input type="hidden" name="area" value={unit.area??""}/><input type="hidden" name="ownership_fraction" value={unit.ownership_fraction??""}/><input type="hidden" name="notes" value={unit.notes??""}/><input type="hidden" name="operational_status" value="inactive"/><button className="button button-destructive" type="submit">Inativar unidade</button></ConfirmedForm></section>}</div>;
}
