"use client";

import { useState } from "react";
import { TriangleAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cancelResourceBlock, createResourceBlock } from "@/lib/reservations/resource-block-actions";

export function ResourceBlocks({ resourceId, reservationMode, blocks = [] }: { resourceId: string; reservationMode: "day" | "time_slot"; blocks?: Array<{ id: string; start_at: string; end_at: string; reason: string }> }) {
  const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [confirming, setConfirming] = useState<typeof blocks[number] | null>(null); const [cancelling, setCancelling] = useState(false);
  const formatDate = (value: string) => new Intl.DateTimeFormat("pt-BR").format(new Date(value));
  const formatTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));
  const confirmCancellation = async () => { if (!confirming || cancelling) return; setCancelling(true); setError(""); const form = new FormData(); form.set("block_id", confirming.id); try { await cancelResourceBlock(form); setConfirming(null); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível cancelar o bloqueio."); } finally { setCancelling(false); } };
  return <div className="cv-resource-blocks"><Button variant="secondary" type="button" onClick={() => setOpen((value) => !value)}>Bloqueios</Button>{open && <section className="cv-panel cv-resource-blocks-panel"><h3>Bloqueios administrativos</h3><form action={async (form) => { try { await createResourceBlock(form); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível criar o bloqueio."); } }} className={`cv-resource-block-form ${reservationMode === "time_slot" ? "is-time-slot" : "is-day"}`}><input type="hidden" name="resource_id" value={resourceId} /><input type="hidden" name="reservation_mode" value={reservationMode} /><label>Data<input name="date" type="date" required /></label>{reservationMode === "time_slot" && <><label>Início<input name="start_time" type="time" required /></label><label>Fim<input name="end_time" type="time" required /></label></>}<label className="cv-resource-block-reason">Motivo<input name="reason" placeholder="Ex.: manutenção do salão" required minLength={2} /></label><Button type="submit">Criar bloqueio</Button></form>{error && <p className="cv-alert cv-alert-error">{error}</p>}<div className="cv-resource-block-list"><h4>Bloqueios ativos</h4>{blocks.length ? blocks.map((block) => <div className="cv-resource-block-item" key={block.id}><span><strong>{formatDate(block.start_at)}</strong>{reservationMode === "time_slot" && <> · {formatTime(block.start_at)}–{formatTime(block.end_at)}</>} · {block.reason}</span><Button variant="destructive" size="compact" type="button" onClick={() => { setError(""); setConfirming(block); }}>Cancelar bloqueio</Button></div>) : <p className="cv-muted">Nenhum bloqueio ativo para este recurso.</p>}</div></section>}{confirming && <div className="cv-feedback-overlay"><section className="cv-feedback-modal cv-resource-block-confirmation" role="dialog" aria-modal="true" aria-labelledby="resource-block-confirm-title"><Button variant="icon" className="cv-feedback-close" type="button" onClick={() => !cancelling && setConfirming(null)} aria-label="Fechar"><X size={18} /></Button><span className="cv-feedback-icon"><TriangleAlert size={28} /></span><h2 id="resource-block-confirm-title">Cancelar bloqueio?</h2><p>Tem certeza de que deseja cancelar este bloqueio? O recurso voltará a ficar disponível para reservas neste período.</p><p className="cv-resource-block-confirm-period">Data: {formatDate(confirming.start_at)}{reservationMode === "time_slot" && <> · Horário: {formatTime(confirming.start_at)}–{formatTime(confirming.end_at)}</>}</p>{error && <p className="cv-alert cv-alert-error">{error}</p>}<div className="cv-resource-actions"><Button variant="secondary" type="button" disabled={cancelling} onClick={() => setConfirming(null)}>Voltar</Button><Button variant="destructive" type="button" disabled={cancelling} onClick={confirmCancellation}>{cancelling ? "Cancelando..." : "Cancelar bloqueio"}</Button></div></section></div>}</div>;
}
