import Link from "next/link";
import { AlertTriangle, ChevronRight, Clock3, Eye, Plus, Search } from "lucide-react";
import { requireCurrentContext, requireUser } from "@/lib/auth/context";
import { createOccurrenceAction, transitionOccurrenceAction } from "@/lib/occurrences/actions";
import { occurrencesListSelect } from "@/lib/occurrences/query";
import { EmptyState, Alert } from "@/components/ui/feedback";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";

export const metadata = { title: "Ocorrências" };
type SearchParams = { new?: string; saved?: string; updated?: string; error?: string; q?: string; status?: string; priority?: string; category?: string; unit?: string };
type Occurrence = { id: string; occurrence_number: number; title: string; priority: string; status: string; confidential: boolean; created_at: string; category: { name?: string } | null; related_unit: { code?: string; display_name?: string | null } | null };
const statusLabels: Record<string, string> = { open: "Aberta", triage: "Em triagem", in_progress: "Em andamento", resolved: "Resolvida", closed: "Encerrada", cancelled: "Cancelada" };
const priorityLabels: Record<string, string> = { low: "Baixa", normal: "Normal", high: "Alta", urgent: "Urgente" };

export default async function OccurrencesPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const { supabase } = await requireUser();
  const context = await requireCurrentContext();
  if (!supabase || context.type !== "condominium") return <section className="no-permission"><h1>Sem acesso</h1></section>;
  const params = await searchParams;
  const q = params.q?.trim() || "";
  const status = ["open", "triage", "in_progress", "resolved", "closed", "cancelled"].includes(params.status || "") ? params.status! : "";
  const priority = ["low", "normal", "high", "urgent"].includes(params.priority || "") ? params.priority! : "";
  const [{ data: categories }, { data: units }, { data: canCreate }] = await Promise.all([
    supabase.from("occurrence_categories").select("id,name,default_priority").eq("condominium_id", context.id).eq("is_active", true).order("sort_order"),
    supabase.from("units").select("id,code,display_name").eq("condominium_id", context.id).eq("operational_status", "active").order("code"),
    supabase.rpc("has_permission", { permission_code: "occurrences.create", target_condominium_id: context.id }),
  ]);
  const category = categories?.some((item) => item.id === params.category) ? params.category! : "";
  const unit = units?.some((item) => item.id === params.unit) ? params.unit! : "";
  const query = supabase.from("occurrences").select(occurrencesListSelect).eq("condominium_id", context.id).order("created_at", { ascending: false }).limit(50);
  if (status) query.eq("status", status);
  if (priority) query.eq("priority", priority);
  if (category) query.eq("category_id", category);
  if (unit) query.eq("related_unit_id", unit);
  if (q) { const number = Number(q); if (Number.isSafeInteger(number) && String(number) === q) query.eq("occurrence_number", number); else query.ilike("title", `%${q.replace(/[%_]/g, "\\$&")}%`); }
  const [{ data: occurrences, error }, counts] = await Promise.all([query, getKpis(supabase, context.id)]);
  const filterQuery = new URLSearchParams();
  for (const [key, value] of [["q", q], ["status", status], ["priority", priority], ["category", category], ["unit", unit]] as const) if (value) filterQuery.set(key, value);
  const newHref = `/app/occurrences?${filterQuery.toString()}${filterQuery.size ? "&" : ""}new=1`;
  const showForm = params.new === "1" && canCreate === true;
  return <div className="cv-page occurrences-v2">
    {params.error && <Alert tone="error">{params.error}</Alert>}{params.saved && <Alert tone="success">Ocorrência criada.</Alert>}{params.updated && <Alert tone="success">Ocorrência atualizada.</Alert>}
    <div className="breadcrumbs"><Link href="/app/dashboard">Início</Link><ChevronRight size={13}/><strong>Ocorrências</strong></div>
    <section className="v2-page-header"><div><p className="page-overline">GESTÃO OPERACIONAL</p><h1>Ocorrências</h1><p>Registre e acompanhe solicitações do condomínio.</p></div>{canCreate === true && <Link className="button button-primary" href={newHref}><Plus size={17}/> Nova ocorrência</Link>}</section>
    <section className="v2-kpi-grid occurrences-kpis"><Kpi icon={<AlertTriangle size={17}/>} label="Abertas" value={counts.open} className="occurrence-open"/><Kpi icon={<Clock3 size={17}/>} label="Em triagem" value={counts.triage} className="occurrence-triage"/><Kpi icon={<Eye size={17}/>} label="Em andamento" value={counts.inProgress} className="occurrence-progress"/><Kpi icon={<AlertTriangle size={17}/>} label="Urgentes" value={counts.urgent} className="occurrence-urgent"/></section>
    {showForm && <section className="cv-panel occurrence-create-panel"><div className="cv-panel-heading"><div><h2>Nova ocorrência</h2><p>Registre uma solicitação usando os dados reais do condomínio.</p></div><Link className="button button-secondary" href={filterQuery.size ? `/app/occurrences?${filterQuery.toString()}` : "/app/occurrences"}>Cancelar</Link></div><form action={createOccurrenceAction} className="cv-form-grid occurrence-form"><label>Categoria<select name="category_id" required><option value="">Selecione</option>{(categories || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Título<input name="title" required minLength={3} maxLength={180}/></label><label className="full">Descrição<textarea name="description" required minLength={3} maxLength={10000}/></label><label>Prioridade<select name="priority" defaultValue=""><option value="">Padrão da categoria</option><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Unidade relacionada<select name="related_unit_id" defaultValue=""><option value="">Opcional</option>{(units || []).map((item) => <option key={item.id} value={item.id}>{item.code}{item.display_name ? ` — ${item.display_name}` : ""}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" name="confidential"/> Relato confidencial</label><input type="hidden" name="origin" value="resident"/><Button type="submit">Abrir ocorrência</Button></form></section>}
    <section className="cv-panel occurrences-list-panel"><form className="cv-filters occurrences-filters" method="get"><label className="cv-search"><Search size={17}/><input name="q" defaultValue={q} placeholder="Buscar por número ou título" aria-label="Buscar por número ou título"/></label><label>Status<select name="status" defaultValue={status}><option value="">Todos</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Prioridade<select name="priority" defaultValue={priority}><option value="">Todas</option>{Object.entries(priorityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Categoria<select name="category" defaultValue={category}><option value="">Todas</option>{(categories || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Unidade<select name="unit" defaultValue={unit}><option value="">Todas</option>{(units || []).map((item) => <option key={item.id} value={item.id}>{item.code}{item.display_name ? ` — ${item.display_name}` : ""}</option>)}</select></label><Button variant="secondary" type="submit">Filtrar</Button>{filterQuery.size > 0 && <Link className="button button-ghost" href="/app/occurrences">Limpar</Link>}</form>
      {error ? <Alert tone="error">Não foi possível carregar as ocorrências.</Alert> : !occurrences?.length ? <EmptyState title={filterQuery.size ? "Nenhuma ocorrência encontrada" : "Nenhuma ocorrência registrada"} description={filterQuery.size ? "Ajuste a busca ou os filtros para ver outros resultados." : "As ocorrências registradas aparecerão aqui."}/> : <><div className="cv-table-wrap"><table className="cv-table occurrences-table"><thead><tr><th>Ocorrência</th><th>Título</th><th>Unidade</th><th>Prioridade</th><th>Status</th><th>Abertura</th><th>Ações</th></tr></thead><tbody>{(occurrences as unknown as Occurrence[]).map((item) => <tr key={item.id}><td><Link className="occurrence-number" href={`/app/occurrences/${item.id}`}>#{item.occurrence_number}</Link></td><td><Link className="occurrence-title" href={`/app/occurrences/${item.id}`}><strong>{item.title}</strong><small>{item.category?.name || "Sem categoria"}{item.confidential ? " · Confidencial" : ""}</small></Link></td><td>{item.related_unit?.code || "—"}</td><td><span className={`occurrence-badge occurrence-priority-${item.priority}`}>{priorityLabels[item.priority] || item.priority}</span></td><td><StatusBadge variant={item.status === "resolved" ? "success" : item.status === "cancelled" ? "danger" : item.status === "triage" ? "warning" : item.status === "in_progress" ? "info" : "neutral"}>{statusLabels[item.status] || item.status}</StatusBadge></td><td><time dateTime={item.created_at}>{formatDate(item.created_at)}</time></td><td><div className="occurrence-row-actions">{item.status === "open" && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={item.id}/><input type="hidden" name="action" value="triage"/><Button variant="secondary" size="compact" type="submit">Triar</Button></form>}{item.status === "resolved" && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={item.id}/><input type="hidden" name="action" value="close"/><Button variant="secondary" size="compact" type="submit">Encerrar</Button></form>}</div></td></tr>)}</tbody></table></div><div className="cv-person-cards occurrence-cards">{(occurrences as unknown as Occurrence[]).map((item) => <Link className="cv-person-card" href={`/app/occurrences/${item.id}`} key={item.id}><span><strong>#{item.occurrence_number} · {item.title}</strong><small>{item.category?.name || "Sem categoria"} · {item.related_unit?.code || "Sem unidade"}</small></span><small>{statusLabels[item.status] || item.status} · {priorityLabels[item.priority] || item.priority}</small><small>{formatDate(item.created_at)}</small></Link>)}</div></>}
    </section>
  </div>;
}

function Kpi({ icon, label, value, className }: { icon: React.ReactNode; label: string; value: number; className: string }) { return <article className={`v2-kpi ${className}`}><span className="v2-kpi-icon">{icon}</span><div><small className="v2-kpi-label">{label}</small><strong>{value}</strong><em>Dados do condomínio</em></div></article>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)); }
async function getKpis(supabase: Awaited<ReturnType<typeof requireUser>>["supabase"], condominiumId: string) { const blank = { open: 0, triage: 0, inProgress: 0, urgent: 0 }; if (!supabase) return blank; const [open, triage, inProgress, urgent] = await Promise.all([supabase.from("occurrences").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).eq("status", "open"), supabase.from("occurrences").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).eq("status", "triage"), supabase.from("occurrences").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).eq("status", "in_progress"), supabase.from("occurrences").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).eq("priority", "urgent").not("status", "in", "(closed,cancelled)")]); return { open: open.count || 0, triage: triage.count || 0, inProgress: inProgress.count || 0, urgent: urgent.count || 0 }; }
