import { getGatehouseDashboardSummary } from "@/lib/gatehouse/data";
import { requireUser } from "@/lib/auth/context";

export type DashboardPeriod = "today" | "7d" | "30d";
export type DashboardActivity = { id: string; type: string; label: string; user: string; at: string; href: string | null };
export type DashboardOccurrence = { id: string; number: number; title: string; category: string; status: string; priority: string; at: string };
export type DashboardImport = { id: string; fileName: string; entity: string; total: number; fresh: number; duplicates: number; invalid: number; user: string; at: string; status: string };
export type DashboardDistribution = { label: string; value: number };
export type CondominiumDashboard = {
  period: DashboardPeriod; timeZone: string; permissions: Record<string, boolean>; condo: { name: string; type: string; status: string; address: string | null };
  units: number | null; residents: number | null; visitorsInside: number | null; packagesWaiting: number | null; reservations: number | null; occurrencesOpen: number | null; occurrencesTriage: number | null; occurrencesUrgent: number | null;
  activity: DashboardActivity[]; inProgress: DashboardOccurrence[]; reservationsByDay: DashboardDistribution[]; occurrenceTypes: DashboardDistribution[]; unitsByStatus: DashboardDistribution[]; imports: DashboardImport[]; error: string | null;
};
export const dashboardPermissionCodes = ["units.read", "residents.read", "gatehouse.read", "reservations.read", "occurrences.read", "imports.read", "occurrences.create", "reservations.resources.read", "people.manage", "gatehouse.manage", "imports.manage"] as const;
export function shouldQueryDashboardModule(permission: boolean) { return permission === true; }
function logDashboardError(block: string, error: { code?: string; message?: string; details?: string; hint?: string } | null | undefined) { if (!error) return; console.error("DASHBOARD_ERROR", `block=${block}`, `code=${error.code || ""}`, `message=${error.message || ""}`, `details=${error.details || ""}`, `hint=${error.hint || ""}`); }
export function applyDashboardCount<T extends { error: { code?: string; message?: string; details?: string; hint?: string } | null }>(result: { error: string | null }, response: T, assign: (value: number) => void, count: number | null | undefined, block = "count") { if (response.error) { logDashboardError(block, response.error); result.error = "Não foi possível carregar todos os dados agora."; return false; } assign(count ?? 0); return true; }
export function dashboardPeriodDays(period: DashboardPeriod) { return period === "today" ? 1 : period === "7d" ? 7 : 30; }
export function aggregateDashboardValues(values: string[]) { const counts = new Map<string, number>(); for (const value of values) counts.set(value, (counts.get(value) || 0) + 1); return [...counts.entries()].map(([label, value]) => ({ label, value })); }
export function aggregateDashboardDates(values: string[], timeZone: string) { return aggregateDashboardValues(values.map((value) => dashboardLocalDate(new Date(value), timeZone))).sort((a, b) => a.label.localeCompare(b.label)); }
export function countActiveUrgentOccurrences(rows: Array<{ priority: string; status: string }>) { return rows.filter((row) => row.priority === "urgent" && !["closed", "cancelled"].includes(row.status)).length; }
export function dashboardLocalDate(date: Date, timeZone: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date); const values = Object.fromEntries(parts.filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; }
function addDays(date: Date, days: number) { const copy = new Date(date); copy.setUTCDate(copy.getUTCDate() + days); return copy; }
function labelEntity(value: string) { return ({ structures: "Estruturas", units: "Unidades", people: "Pessoas", owners: "Proprietários", residents: "Moradores" } as Record<string, string>)[value] || value; }
function formatAddress(address: { street?: string; number?: string | null; city?: string; state?: string } | null) { return address ? [address.street, address.number, address.city, address.state].filter(Boolean).join(", ") : null; }

export async function getCondominiumDashboard(condominiumId: string, period: DashboardPeriod = "today"): Promise<CondominiumDashboard> {
  const { supabase } = await requireUser();
  const blank: CondominiumDashboard = { period, timeZone: "America/Sao_Paulo", permissions: {}, condo: { name: "Condomínio", type: "", status: "", address: null }, units: null, residents: null, visitorsInside: null, packagesWaiting: null, reservations: null, occurrencesOpen: null, occurrencesTriage: null, occurrencesUrgent: null, activity: [], inProgress: [], reservationsByDay: [], occurrenceTypes: [], unitsByStatus: [], imports: [], error: null };
  if (!supabase) return blank;
  const { data: condo, error: condoError } = await supabase.from("condominiums").select("name,condominium_type,status,timezone,addresses(street,number,city,state)").eq("id", condominiumId).maybeSingle(); logDashboardError("condominiums", condoError);
  const timeZone = condo?.timezone || blank.timeZone; const now = new Date(); const today = dashboardLocalDate(now, timeZone); const startDate = addDays(now, -(dashboardPeriodDays(period) - 1)); const start = startDate.toISOString(); const end = addDays(now, 1).toISOString();
  const permissionResults = await Promise.all(dashboardPermissionCodes.map((permission_code) => supabase.rpc("has_permission", { permission_code, target_condominium_id: condominiumId }))); permissionResults.forEach((response, index) => logDashboardError(`has_permission:${dashboardPermissionCodes[index]}`, response.error));
  const permissions = Object.fromEntries(dashboardPermissionCodes.map((code, index) => [code, permissionResults[index].data === true]));
  const result: CondominiumDashboard = { ...blank, timeZone, permissions, period, condo: { name: condo?.name || blank.condo.name, type: condo?.condominium_type || "", status: condo?.status || "", address: formatAddress(condo?.addresses as { street?: string; number?: string | null; city?: string; state?: string } | null) } };
  let dashboardErrorLogged = false;
  const recordError = (error?: { code?: string; message?: string; details?: string; hint?: string } | null, block = "dashboard_query") => { dashboardErrorLogged = true; logDashboardError(block, error || { message: "query error details were not forwarded" }); result.error ||= "Não foi possível carregar todos os dados agora."; };
  const tasks: PromiseLike<unknown>[] = [];
  if (permissions["units.read"]) tasks.push(supabase.from("units").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).eq("operational_status", "active").then((r) => applyDashboardCount(result, r, (v) => { result.units = v; }, r.count, "units")));
  if (permissions["residents.read"]) tasks.push(supabase.from("unit_occupancies").select("id", { count: "exact", head: true }).eq("condominium_id", condominiumId).lte("starts_at", today).or(`ends_at.is.null,ends_at.gt.${today}`).then((r) => applyDashboardCount(result, r, (v) => { result.residents = v; }, r.count, "unit_occupancies")));
  if (permissions["gatehouse.read"]) tasks.push(getGatehouseDashboardSummary(condominiumId).then((s) => { result.visitorsInside = s.insideNowCount; result.packagesWaiting = s.waitingPackagesCount; result.activity.push(...s.recentPackages.slice(0, 8).map((p) => ({ id: `package-${p.id}`, type: "Encomenda", label: "Encomenda recebida", user: "—", at: p.received_at, href: "/app/gatehouse/packages" }))); }));
  if (permissions["reservations.read"]) tasks.push(supabase.from("reservations").select("id,created_at,starts_at,resource:reservable_resources(name)").eq("condominium_id", condominiumId).in("status", ["pending", "approved"]).lt("starts_at", end).gte("ends_at", start).then((r) => { if (r.error) return recordError(r.error, "reservations"); result.reservations = r.data?.length || 0; const buckets = new Map<string, number>(); for (const row of r.data || []) { const day = dashboardLocalDate(new Date(row.starts_at), timeZone); buckets.set(day, (buckets.get(day) || 0) + 1); } result.reservationsByDay = [...buckets.entries()].sort().map(([label, value]) => ({ label, value })); result.activity.push(...(r.data || []).slice(0, 8).map((row) => ({ id: `reservation-${row.id}`, type: "Reserva", label: `Reserva: ${((row.resource as { name?: string } | null)?.name || "recurso")}`, user: "—", at: row.created_at, href: "/app/reservations" }))); }));
  if (permissions["occurrences.read"]) tasks.push(supabase.from("occurrences").select("id,occurrence_number,title,status,priority,created_at,category:occurrence_categories(name)").eq("condominium_id", condominiumId).not("status", "in", "(closed,cancelled)").then((r) => { if (r.error) return recordError(r.error, "occurrences"); const rows = r.data || []; result.occurrencesOpen = rows.filter((x) => x.status === "open").length; result.occurrencesTriage = rows.filter((x) => x.status === "triage").length; result.occurrencesUrgent = rows.filter((x) => x.priority === "urgent").length; result.inProgress = rows.slice(0, 8).map((x) => ({ id: x.id, number: x.occurrence_number, title: x.title, category: ((x.category as { name?: string } | null)?.name || "—"), status: x.status, priority: x.priority, at: x.created_at })); const types = new Map<string, number>(); for (const row of rows.filter((x) => x.created_at >= start && x.created_at < end)) { const name = (row.category as { name?: string } | null)?.name || "Sem categoria"; types.set(name, (types.get(name) || 0) + 1); } result.occurrenceTypes = [...types.entries()].map(([label, value]) => ({ label, value })); result.activity.push(...rows.filter((x) => x.created_at >= start && x.created_at < end).slice(0, 8).map((x) => ({ id: `occurrence-${x.id}`, type: "Ocorrência", label: x.title, user: "—", at: x.created_at, href: "/app/occurrences" }))); }));
  if (permissions["units.read"]) tasks.push(supabase.from("units").select("operational_status").eq("condominium_id", condominiumId).then((r) => { if (r.error) return recordError(r.error, "unit_status_distribution"); const buckets = new Map<string, number>(); for (const row of r.data || []) buckets.set(row.operational_status, (buckets.get(row.operational_status) || 0) + 1); result.unitsByStatus = [...buckets.entries()].map(([label, value]) => ({ label, value })); }));
  if (permissions["imports.read"]) tasks.push(supabase.from("import_batches").select("id,file_name,entity_type,total_rows,new_rows,duplicate_rows,invalid_rows,created_at,status,created_by_user_account_id").eq("condominium_id", condominiumId).order("created_at", { ascending: false }).limit(8).then((r) => { if (r.error) return recordError(r.error, "import_batches"); result.imports = (r.data || []).map((x) => ({ id: x.id, fileName: x.file_name, entity: labelEntity(x.entity_type), total: x.total_rows, fresh: x.new_rows, duplicates: x.duplicate_rows, invalid: x.invalid_rows, user: "—", at: x.created_at, status: x.status })); }));
  await Promise.all(tasks); if (result.error && !dashboardErrorLogged) logDashboardError("unknown_partial_load", { message: "partial load alert set without granular diagnostic" }); result.activity = result.activity.sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime()).slice(0, 8); return result;
}
