import { notFound } from "next/navigation";
import Link from "next/link";
import { ChevronRight } from "lucide-react";
import { requireCurrentContext, requireUser } from "@/lib/auth/context";
import { addOccurrenceCommentAction, transitionOccurrenceAction } from "@/lib/occurrences/actions";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";

type AssigneeRow = { user_account_id: string; user_accounts?: { people?: { full_name?: string; preferred_name?: string } | null } | null };

const statusLabels: Record<string, string> = { open: "Aberta", triage: "Em triagem", in_progress: "Em andamento", resolved: "Resolvida", closed: "Encerrada", cancelled: "Cancelada" };
const priorityLabels: Record<string, string> = { low: "Baixa", normal: "Normal", high: "Alta", urgent: "Urgente" };
const eventLabels: Record<string, string> = { created: "Criada", triage: "Enviada para triagem", assigned: "Responsável atribuído", resolved: "Resolvida", closed: "Encerrada", reopened: "Reaberta", cancelled: "Cancelada" };
const statusBadgeVariants: Record<string, "success" | "neutral" | "warning" | "danger" | "info"> = { open: "success", triage: "warning", in_progress: "info", resolved: "success", closed: "neutral", cancelled: "danger" };
const priorityBadgeVariants: Record<string, "success" | "neutral" | "warning" | "danger" | "info"> = { low: "neutral", normal: "info", high: "warning", urgent: "danger" };

export default async function OccurrenceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [{ id }, { supabase }, context] = await Promise.all([params, requireUser(), requireCurrentContext()]);
  if (!supabase || context.type !== "condominium") return notFound();
  const [{ data: occurrence, error: occurrenceError }, { data: comments }, { data: history }, { data: assigneeRows }] = await Promise.all([
    supabase.from("occurrences").select("*, category:occurrence_categories!occurrences_category_id_condominium_id_fkey(name)").eq("id", id).eq("condominium_id", context.id).maybeSingle(),
    supabase.from("occurrence_comments").select("id,body,visibility,created_at,author_user_account_id").eq("occurrence_id", id).eq("condominium_id", context.id),
    supabase.from("occurrence_history").select("id,event_type,previous_status,new_status,reason,created_at").eq("occurrence_id", id).eq("condominium_id", context.id),
    supabase.from("role_assignments").select("user_account_id,user_accounts(id,people(full_name,preferred_name)),roles!inner(code)").eq("condominium_id", context.id).eq("status", "active").in("roles.code", ["condominium.syndic", "condominium.manager"]),
  ]);
  if (!occurrence || occurrenceError) return notFound();
  const sortedComments = [...(comments || [])].sort((a, b) => String(a.created_at).localeCompare(String(b.created_at)));
  const sortedHistory = [...(history || [])].sort((a, b) => String(a.created_at).localeCompare(String(b.created_at)));
  const assignees = (assigneeRows || []) as AssigneeRow[];
  const hasAvailableActions = ["open", "triage", "in_progress", "resolved"].includes(occurrence.status);
  return <div className="cv-page occurrences-v2 occurrence-detail-page"><div className="breadcrumbs"><Link href="/app/dashboard">Início</Link><ChevronRight size={13}/><Link href="/app/occurrences">Ocorrências</Link><ChevronRight size={13}/><strong>#{occurrence.occurrence_number}</strong></div><section className="v2-page-header occurrence-detail-header"><div className="occurrence-detail-heading"><div className="occurrence-detail-kicker"><span className="page-overline">OCORRÊNCIA #{occurrence.occurrence_number}</span><span className="occurrence-detail-category">{occurrence.category?.name || "Sem categoria"}</span></div><h1>{occurrence.title}</h1><p>Registro de ocorrência do condomínio</p></div><div className="occurrence-detail-badges" aria-label="Status e prioridade"><StatusBadge variant={statusBadgeVariants[occurrence.status] || "neutral"}>{statusLabels[occurrence.status] || occurrence.status}</StatusBadge><StatusBadge variant={priorityBadgeVariants[occurrence.priority] || "neutral"}>{priorityLabels[occurrence.priority] || occurrence.priority}</StatusBadge></div></section>
    <div className="occurrence-detail-grid"><main className="occurrence-detail-main"><section className="cv-panel occurrence-detail-panel occurrence-description-panel"><div className="cv-panel-heading"><div><span className="occurrence-section-eyebrow">Registro principal</span><h2>Descrição</h2><p>Informações registradas na abertura da ocorrência.</p></div></div><p className="occurrence-description">{occurrence.description || "Nenhuma descrição informada."}</p><dl className="occurrence-meta"><div><dt>Origem</dt><dd>{occurrence.origin}</dd></div><div><dt>Confidencialidade</dt><dd>{occurrence.confidential ? "Confidencial" : "Condomínio"}</dd></div><div><dt>Aberta em</dt><dd>{new Date(occurrence.created_at).toLocaleString("pt-BR")}</dd></div>{occurrence.resolution && <div><dt>Resolução</dt><dd>{occurrence.resolution}</dd></div>}</dl></section>
    {hasAvailableActions && <section className="cv-panel occurrence-detail-panel occurrence-actions-panel"><div className="cv-panel-heading"><div><span className="occurrence-section-eyebrow">Próximo passo</span><h2>Ações disponíveis</h2><p>As ações respeitam o status e as permissões do seu perfil.</p></div></div><div className="cv-actions occurrence-actions">
      {occurrence.status === "open" && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="triage"/><Button variant="secondary" type="submit">Iniciar triagem</Button></form>}
      {occurrence.status === "triage" && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="assign"/><select name="assignee_user_account_id" required><option value="">Selecione o responsável</option>{assignees.map((row) => <option key={row.user_account_id} value={row.user_account_id}>{row.user_accounts?.people?.preferred_name || row.user_accounts?.people?.full_name || row.user_account_id}</option>)}</select><Button variant="secondary" type="submit">Atribuir</Button></form>}
      {occurrence.status === "in_progress" && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="resolve"/><input name="reason" required placeholder="Descreva a resolução"/><Button type="submit">Resolver</Button></form>}
      {occurrence.status === "resolved" && <><form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="close"/><Button type="submit">Encerrar</Button></form><form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="reopen"/><input name="reason" required placeholder="Motivo da reabertura"/><Button variant="secondary" type="submit">Reabrir</Button></form></>}
      {["open", "triage", "in_progress"].includes(occurrence.status) && <form action={transitionOccurrenceAction}><input type="hidden" name="occurrence_id" value={id}/><input type="hidden" name="action" value="cancel"/><input name="reason" required placeholder="Motivo do cancelamento"/><Button variant="destructive" type="submit">Cancelar</Button></form>}
    </div></section>}
    <section className="cv-panel occurrence-detail-panel occurrence-comments-panel"><div className="cv-panel-heading"><div><span className="occurrence-section-eyebrow">Colaboração</span><h2>Comentários</h2><p>{sortedComments.length ? `${sortedComments.length} registro${sortedComments.length === 1 ? "" : "s"}` : "Nenhum comentário registrado"}</p></div></div><div className="occurrence-comments">{sortedComments.map((comment) => <article key={comment.id} className="occurrence-comment"><strong>{comment.visibility === "internal" ? "Interno" : "Solicitante"}</strong><p>{comment.body}</p></article>)}</div><form action={addOccurrenceCommentAction} className="cv-form-grid occurrence-comment-form"><input type="hidden" name="occurrence_id" value={id}/><label className="occurrence-comment-body"><span>Adicionar comentário</span><textarea name="body" required minLength={1} placeholder="Escreva uma atualização para esta ocorrência"/></label><label className="occurrence-comment-visibility">Visibilidade<select name="visibility" defaultValue="requester"><option value="requester">Solicitante</option><option value="internal">Interno</option></select></label><Button type="submit">Comentar</Button></form></section>
    <section className="cv-panel occurrence-detail-panel occurrence-history-panel"><div className="cv-panel-heading"><div><span className="occurrence-section-eyebrow">Linha do tempo</span><h2>Histórico</h2><p>Movimentações em ordem cronológica.</p></div></div><ol className="occurrence-timeline">{sortedHistory.map((event) => <li key={event.id}><span className="occurrence-timeline-dot" aria-hidden="true"/><div className="occurrence-timeline-card"><div className="occurrence-timeline-topline"><strong>{eventLabels[event.event_type] || event.event_type}</strong><time>{new Date(event.created_at).toLocaleString("pt-BR")}</time></div><p>{event.previous_status ? `${statusLabels[event.previous_status] || event.previous_status}${event.new_status ? ` → ${statusLabels[event.new_status] || event.new_status}` : ""}` : "Registro criado"}</p>{event.reason && <small>{event.reason}</small>}</div></li>)}</ol></section></main><aside className="occurrence-detail-aside"><section className="cv-panel occurrence-detail-summary"><span className="occurrence-section-eyebrow">Visão rápida</span><h2>Resumo</h2><div><span>Status</span><strong>{statusLabels[occurrence.status] || occurrence.status}</strong></div><div><span>Prioridade</span><strong>{priorityLabels[occurrence.priority] || occurrence.priority}</strong></div><div><span>Categoria</span><strong>{occurrence.category?.name || "Sem categoria"}</strong></div></section></aside></div>
  </div>;
}
