import type { Metadata } from "next";
import Link from "next/link";
import { Activity, AlertTriangle, CalendarDays, ChevronRight, FileUp, Home, Package, Plus, ShieldAlert, UserRound, Users } from "lucide-react";
import { DashboardPeriodFilter } from "@/components/dashboard/dashboard-period-filter";
import { EmptyState } from "@/components/ui/feedback";
import { requireCurrentContext } from "@/lib/auth/context";
import { redirect } from "next/navigation";
import { getCondominiumDashboard, type DashboardDistribution, type DashboardPeriod } from "@/lib/dashboard/data";
import { formatDateTimeInTimezone } from "@/lib/gatehouse/timezone";
export const metadata: Metadata = { title: "Painel" };
const periods = new Set<DashboardPeriod>(["today", "7d", "30d"]);
const iconMap = { units: Home, residents: Users, visitors: UserRound, packages: Package, reservations: CalendarDays, open: Activity, triage: ShieldAlert, urgent: AlertTriangle };
function Kpi({ id, label, value, note, permission }: { id: keyof typeof iconMap; label: string; value: number | null; note?: string; permission: boolean }) { if (!permission) return null; const Icon = iconMap[id]; return <article className={`v2-kpi v2-kpi-${id}`}><span className="v2-kpi-icon"><Icon size={17} /></span><div><small>{label}</small><strong>{value ?? "—"}</strong>{note && <em>{note}</em>}</div></article>; }
function Distribution({ title, items, empty }: { title: string; items: DashboardDistribution[]; empty: string }) { const total = items.reduce((sum, item) => sum + item.value, 0); return <section className="cv-panel v2-analytic"><h2>{title}</h2>{!items.length ? <EmptyState title={empty} description="Nenhum dado real disponível para o período selecionado." /> : <div className="v2-bars">{items.map((item) => <div className="v2-bar-row" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: (total ? Math.max(3, item.value / total * 100) : 0) + "%" }} /></div><strong>{item.value}</strong></div>)}</div>}</section>; }
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ period?: string }> }) {
  const context = await requireCurrentContext(); if (context.type === "platform") redirect("/app/platform"); if (context.type !== "condominium") return null;
  const requested = (await searchParams).period; const period = periods.has(requested as DashboardPeriod) ? requested as DashboardPeriod : "today"; const dashboard = await getCondominiumDashboard(context.id, period); const p = dashboard.permissions;
  const quick = [{ label: "Nova ocorrência", href: "/app/occurrences", icon: Plus, show: p["occurrences.create"] }, { label: "Nova reserva", href: "/app/reservations", icon: CalendarDays, show: p["reservations.resources.read"] }, { label: "Novo morador", href: "/app/condominium/people/new", icon: Users, show: p["people.manage"] }, { label: "Registrar encomenda", href: "/app/gatehouse/packages", icon: Package, show: p["gatehouse.manage"] }, { label: "Importar dados", href: "/app/condominium/imports", icon: FileUp, show: p["imports.manage"] }].filter((item) => item.show);
  return <div className="cv-page dashboard-v2"><div className="breadcrumbs"><Link href="/app/dashboard">Início</Link><ChevronRight size={13} /><strong>Painel</strong></div>
    <header className="v2-page-header"><div><p className="page-overline">PAINEL</p><h1>{dashboard.condo.name}</h1><p>Visão operacional do condomínio e das atividades recentes.</p></div><DashboardPeriodFilter period={period} /></header>
    <section className="v2-kpi-grid" aria-label="Indicadores do painel"><Kpi id="units" label="Unidades" value={dashboard.units} permission={Boolean(p["units.read"])} /><Kpi id="residents" label="Moradores" value={dashboard.residents} note="Vínculos vigentes" permission={Boolean(p["residents.read"])} /><Kpi id="visitors" label="Visitantes" value={dashboard.visitorsInside} note="Dentro agora" permission={Boolean(p["gatehouse.read"])} /><Kpi id="packages" label="Encomendas" value={dashboard.packagesWaiting} note="Aguardando retirada" permission={Boolean(p["gatehouse.read"])} /><Kpi id="reservations" label="Reservas" value={dashboard.reservations} permission={Boolean(p["reservations.read"])} /><Kpi id="open" label="Ocorrências abertas" value={dashboard.occurrencesOpen} permission={Boolean(p["occurrences.read"])} /><Kpi id="triage" label="Em triagem" value={dashboard.occurrencesTriage} permission={Boolean(p["occurrences.read"])} /><Kpi id="urgent" label="Urgentes" value={dashboard.occurrencesUrgent} permission={Boolean(p["occurrences.read"])} /></section>
    {dashboard.error && <div className="alert alert-error">{dashboard.error}</div>}
    <div className="v2-main-grid"><main className="v2-main-column">
      <section className="cv-panel v2-panel"><div className="v2-panel-heading"><div><h2>Atividade recente</h2><p>Eventos disponíveis nos módulos autorizados.</p></div></div>{dashboard.activity.length ? <div className="v2-activity-table"><div className="v2-table-head"><span>Tipo</span><span>Descrição</span><span>Usuário</span><span>Data/hora</span><span /></div>{dashboard.activity.map((item) => <div className="v2-table-row" key={item.id}><span className="v2-type">{item.type}</span><strong>{item.label}</strong><span>{item.user}</span><time dateTime={item.at}>{formatDateTimeInTimezone(item.at, dashboard.timeZone)}</time><span>{item.href && <Link href={item.href}>Ver todas</Link>}</span></div>)}</div> : <EmptyState title="Nenhuma atividade recente" description="As atividades disponíveis aparecerão aqui quando houver movimentação." />}</section>
      <section className="cv-panel v2-panel"><div className="v2-panel-heading"><div><h2>Ocorrências em andamento</h2><p>Registros ainda ativos na operação.</p></div>{p["occurrences.read"] && <Link href="/app/occurrences">Ver todas</Link>}</div>{dashboard.inProgress.length ? <div className="v2-occurrences">{dashboard.inProgress.map((item) => <div className="v2-occurrence" key={item.id}><strong>#{item.number} {item.title}</strong><span>{item.category}</span><b className={"v2-status v2-status-" + item.status}>{item.status}</b><small>{formatDateTimeInTimezone(item.at, dashboard.timeZone)}</small></div>)}</div> : <EmptyState title="Nenhuma ocorrência em andamento" description="O painel será preenchido quando houver ocorrências ativas." />}</section>
      <div className="v2-analytics"><Distribution title="Reservas por período" items={dashboard.reservationsByDay} empty="Nenhuma reserva no período" /><Distribution title="Tipos de ocorrências" items={dashboard.occurrenceTypes} empty="Nenhuma ocorrência no período" /><Distribution title="Unidades por status" items={dashboard.unitsByStatus} empty="Nenhuma unidade disponível" /></div>
      <section className="cv-panel v2-panel"><div className="v2-panel-heading"><div><h2>Últimas importações</h2><p>Histórico somente leitura dos lotes registrados.</p></div>{p["imports.read"] && <Link href="/app/condominium/imports">Ver todas</Link>}</div>{dashboard.imports.length ? <div className="v2-import-list">{dashboard.imports.map((item) => <div className="v2-import-row" key={item.id}><strong>{item.fileName}</strong><span>{item.entity}</span><span>{item.total} linhas</span><span>{item.fresh} novos</span><span>{item.duplicates} dup.</span><span>{item.invalid} inválidos</span><b>{item.status}</b><time>{formatDateTimeInTimezone(item.at, dashboard.timeZone)}</time></div>)}</div> : <EmptyState title="Nenhuma importação registrada" description="Os lotes concluídos aparecerão aqui quando existirem." />}</section>
    </main><aside className="v2-side-column"><section className="cv-panel v2-panel"><h2>Ações rápidas</h2>{quick.length ? <nav className="v2-quick-actions">{quick.map((item) => <Link href={item.href} key={item.label}><item.icon size={16} />{item.label}</Link>)}</nav> : <EmptyState title="Nenhuma ação disponível" description="As ações dependem do fluxo e da permissão do usuário." />}</section><section className="cv-panel v2-panel"><h2>Informações do condomínio</h2><dl className="v2-condo-info"><div><dt>Nome</dt><dd>{dashboard.condo.name}</dd></div><div><dt>Tipo</dt><dd>{dashboard.condo.type || "Não informado"}</dd></div><div><dt>Endereço</dt><dd>{dashboard.condo.address || "Não informado"}</dd></div><div><dt>Unidades</dt><dd>{dashboard.units ?? "—"}</dd></div><div><dt>Moradores</dt><dd>{dashboard.residents ?? "—"}</dd></div><div><dt>Status</dt><dd>{dashboard.condo.status || "—"}</dd></div></dl></section></aside></div>
  </div>;
}
