import { EmptyState } from "@/components/ui/feedback";
import { PersonRelationshipForm } from "@/components/condominium/person-form";
import { occupancyTypeLabels } from "@/lib/condominium/format";
import Link from "next/link";
import { Plus, Search, Users, Building2 } from "lucide-react";

export type RelationshipRow={id:string;person_id:string;unit_id:string;starts_at:string;ends_at:string|null;ownership_percentage?:number|null;occupancy_type?:string;is_primary?:boolean;person_name:string;unit_code:string;unit_name:string|null;structure_id:string|null;structure_name:string};
export function RelationshipIndex({kind,rows,people,units,mode,today,canManage,returnTo,selectedPersonId,showForm=false,q="",structureId="",unitId="",occupancyType=""}:{kind:"ownership"|"occupancy";rows:RelationshipRow[];people:{id:string;full_name:string}[];units:{id:string;code:string;display_name:string|null;structure_id:string|null;structure_name:string;operational_status:string}[];mode:string;today:string;canManage:boolean;returnTo:string;selectedPersonId?:string;showForm?:boolean;q?:string;structureId?:string;unitId?:string;occupancyType?:string}) {
  const needle=q.trim().toLocaleLowerCase("pt-BR");
  const filtered=rows.filter((r)=>{
    const dateMatches=mode==="all"?true:mode==="current"?r.starts_at<=today&&(!r.ends_at||r.ends_at>today):mode==="future"?r.starts_at>today:!!r.ends_at&&r.ends_at<=today;
    const searchMatches=!needle||`${r.person_name} ${r.unit_name||""} ${r.unit_code} ${r.structure_name}`.toLocaleLowerCase("pt-BR").includes(needle);
    return dateMatches&&searchMatches&&(!structureId||r.structure_id===structureId)&&(!unitId||r.unit_id===unitId)&&(kind!=="occupancy"||!occupancyType||r.occupancy_type===occupancyType);
  });
  const structures=[...new Map(units.filter((unit)=>unit.structure_id).map((unit)=>[unit.structure_id!,{id:unit.structure_id!,name:unit.structure_name}])).values()].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));
  const title=kind==="ownership"?"Proprietários":"Moradores";
  const currentRows=rows.filter((r)=>r.starts_at<=today&&(!r.ends_at||r.ends_at>today));
  const occupiedUnits=new Set(currentRows.map((r)=>r.unit_id)).size;
  const formQuery=new URLSearchParams(returnTo.split("?")[1]||""); formQuery.set("new","1");
  const closeHref=returnTo;
  return <div className="cv-page">
    <section className="v2-page-header"><div><p className="page-overline">CONDOMÍNIO</p><h1>{title}</h1><p>Gerencie os moradores do condomínio.</p></div>{canManage&&<Link className="button button-primary" href={`?${formQuery.toString()}`}><Plus size={17}/> Novo morador</Link>}</section>
    <section className="v2-kpi-grid v2-resident-kpis"><article className="v2-kpi v2-kpi-residents"><span className="v2-kpi-icon"><Users size={17}/></span><div><small>Moradores vigentes</small><strong>{currentRows.length}</strong><em>Vínculos ativos hoje</em></div></article><article className="v2-kpi v2-kpi-units"><span className="v2-kpi-icon"><Building2 size={17}/></span><div><small>Unidades com moradores</small><strong>{occupiedUnits}</strong><em>Unidades com vínculo vigente</em></div></article></section>
    <section className="cv-panel v2-residents-panel"><form className="cv-filters v2-resident-filters" method="get"><label className="cv-search"><Search size={17}/><input name="q" defaultValue={q} placeholder="Buscar por nome, unidade ou estrutura" aria-label="Buscar por nome, unidade ou estrutura"/></label><label>Estrutura<select name="structure" defaultValue={structureId}><option value="">Todas</option>{structures.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Unidade<select name="unit" defaultValue={unitId}><option value="">Todas</option>{units.map((u)=><option key={u.id} value={u.id}>{u.display_name||u.code}</option>)}</select></label>{kind==="occupancy"&&<label>Tipo<select name="type" defaultValue={occupancyType}><option value="">Todos</option><option value="owner">Proprietário</option><option value="tenant">Inquilino</option><option value="family_member">Familiar</option><option value="dependent">Dependente</option><option value="other">Outro</option></select></label>}<label>Situação<select name="mode" defaultValue={mode}><option value="current">Vigente hoje</option><option value="future">Futuro</option><option value="ended">Encerrado</option><option value="all">Todos</option></select></label><button className="button button-outline" type="submit">Filtrar</button></form>
      {!filtered.length?<EmptyState title="Nenhum vínculo neste filtro" description="Ajuste o filtro ou cadastre um vínculo abaixo."/>:<><div className="cv-table-wrap"><table className="cv-table v2-residents-table"><thead><tr><th>Pessoa</th><th>Unidade</th><th>Tipo</th><th>Vigência</th></tr></thead><tbody>{filtered.map((r)=><tr key={r.id}><td><span className="v2-resident-person"><span className="v2-resident-avatar" aria-hidden="true">{initials(r.person_name)}</span><strong>{r.person_name}</strong></span></td><td><strong>{r.unit_name||r.unit_code}</strong><small>{r.structure_name}</small></td><td><span className="v2-resident-type">{occupancyTypeLabels[r.occupancy_type||""]||"Outro"}{r.is_primary&&<b>Principal</b>}</span></td><td><span className="v2-resident-date">{r.starts_at} → {r.ends_at||"sem término"}</span></td></tr>)}</tbody></table></div><div className="cv-person-cards">{filtered.map((r)=><article className="cv-person-card" key={r.id}><span><strong>{r.person_name}</strong><small>{r.unit_name||r.unit_code}</small></span><small>{occupancyTypeLabels[r.occupancy_type||""]||"Outro"}{r.is_primary&&" · Principal"}</small><small>{r.starts_at} → {r.ends_at||"sem término"}</small></article>)}</div></>}</section>
    {showForm&&canManage&&<section className="cv-panel v2-resident-form"><div className="cv-panel-heading"><div><h2>Novo morador</h2><p>A pessoa deve estar vinculada a este condomínio. Períodos históricos são preservados.</p></div><Link className="button button-outline button-small" href={closeHref}>Cancelar</Link></div><PersonRelationshipForm people={people} units={units} kind={kind} returnTo={returnTo} selectedPersonId={selectedPersonId}/></section>}
  </div>;
}

function initials(name:string) { return name.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase(); }
