import { EmptyState } from "@/components/ui/feedback";
import { PersonRelationshipForm } from "@/components/condominium/person-form";

export type RelationshipRow={id:string;person_id:string;unit_id:string;starts_at:string;ends_at:string|null;ownership_percentage?:number|null;occupancy_type?:string;is_primary?:boolean;person_name:string;unit_code:string;unit_name:string|null;structure_id:string|null;structure_name:string};
export function RelationshipIndex({kind,rows,people,units,mode,today,canManage,returnTo,selectedPersonId,q="",structureId="",unitId="",occupancyType=""}:{kind:"ownership"|"occupancy";rows:RelationshipRow[];people:{id:string;full_name:string}[];units:{id:string;code:string;display_name:string|null;structure_id:string|null;structure_name:string;operational_status:string}[];mode:string;today:string;canManage:boolean;returnTo:string;selectedPersonId?:string;q?:string;structureId?:string;unitId?:string;occupancyType?:string}) {
  const needle=q.trim().toLocaleLowerCase("pt-BR");
  const filtered=rows.filter((r)=>{
    const dateMatches=mode==="all"?true:mode==="current"?r.starts_at<=today&&(!r.ends_at||r.ends_at>today):mode==="future"?r.starts_at>today:!!r.ends_at&&r.ends_at<=today;
    const searchMatches=!needle||`${r.person_name} ${r.unit_name||""} ${r.unit_code} ${r.structure_name}`.toLocaleLowerCase("pt-BR").includes(needle);
    return dateMatches&&searchMatches&&(!structureId||r.structure_id===structureId)&&(!unitId||r.unit_id===unitId)&&(kind!=="occupancy"||!occupancyType||r.occupancy_type===occupancyType);
  });
  const structures=[...new Map(units.filter((unit)=>unit.structure_id).map((unit)=>[unit.structure_id!,{id:unit.structure_id!,name:unit.structure_name}])).values()].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));
  const title=kind==="ownership"?"Proprietários":"Moradores";
  return <div className="cv-page">
    <section className="page-heading"><div><p className="page-overline">CONDOMÍNIO</p><h1>{title}</h1><p>{kind==="ownership"?"Propriedade e participação das unidades.":"Pessoas vinculadas à moradia das unidades."}</p></div></section>
    <section className="cv-panel"><form className="cv-filters" method="get"><label className="cv-search"><input name="q" defaultValue={q} placeholder="Buscar pessoa, unidade ou estrutura" aria-label="Buscar pessoa, unidade ou estrutura"/></label><label>Estrutura<select name="structure" defaultValue={structureId}><option value="">Todas</option>{structures.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Unidade<select name="unit" defaultValue={unitId}><option value="">Todas</option>{units.map((u)=><option key={u.id} value={u.id}>{u.display_name||u.code}</option>)}</select></label>{kind==="occupancy"&&<label>Tipo<select name="type" defaultValue={occupancyType}><option value="">Todos</option><option value="owner">Proprietário</option><option value="tenant">Inquilino</option><option value="family_member">Familiar</option><option value="dependent">Dependente</option><option value="other">Outro</option></select></label>}<label>Situação<select name="mode" defaultValue={mode}><option value="current">Vigente hoje</option><option value="future">Futuro</option><option value="ended">Encerrado</option><option value="all">Todos</option></select></label><button className="button button-secondary" type="submit">Filtrar</button></form>
      {!filtered.length?<EmptyState title="Nenhum vínculo neste filtro" description="Ajuste o filtro ou cadastre um vínculo abaixo."/>:<><div className="cv-table-wrap"><table className="cv-table"><thead><tr><th>Pessoa</th><th>Unidade</th>{kind==="ownership"?<th>Participação</th>:<th>Tipo</th>}<th>Vigência</th></tr></thead><tbody>{filtered.map((r)=><tr key={r.id}><td>{r.person_name}</td><td>{r.unit_name||r.unit_code}</td><td>{kind==="ownership"?r.ownership_percentage===null?"Não informada":`${r.ownership_percentage}%`:`${r.occupancy_type||"outro"}${r.is_primary?" · Principal":""}`}</td><td>{r.starts_at} → {r.ends_at||"sem término"}</td></tr>)}</tbody></table></div><div className="cv-person-cards">{filtered.map((r)=><article className="cv-person-card" key={r.id}><span><strong>{r.person_name}</strong><small>{r.unit_name||r.unit_code}</small></span><small>{kind==="ownership"?r.ownership_percentage===null?"Participação não informada":`${r.ownership_percentage}%`:`${r.occupancy_type||"outro"}${r.is_primary?" · Principal":""}`}</small><small>{r.starts_at} → {r.ends_at||"sem término"}</small></article>)}</div></>}</section>
    {canManage&&<section className="cv-panel"><h2>{kind==="ownership"?"Registrar proprietário":"Registrar morador"}</h2><p className="cv-muted">A pessoa deve estar vinculada a este condomínio. Períodos históricos são preservados.</p><PersonRelationshipForm people={people} units={units} kind={kind} returnTo={returnTo} selectedPersonId={selectedPersonId}/></section>}
  </div>;
}
